use_frameworks!

platform :ios, '10.0'

target 'KeyPath-Theme-Manager_Example' do
  pod 'KeyPath-Theme-Manager', :path => '../'
  pod 'Sluthware', :git => 'https://github.com/patsluth/Sluthware.git'
end
