use_frameworks!

platform :ios, '9.0'

target 'KeyPath-Theme-Manager_Example' do
  pod 'KeyPath-Theme-Manager', :path => '../'
  pod 'Sluthware', :git => 'https://github.com/patsluth/Sluthware.git'

  target 'KeyPath-Theme-Manager_Tests' do
    inherit! :search_paths

    
  end
end
